app/forms/login.py
from flask_wtf import FlaskForm
from wtforms import Form, StringField, PasswordField, SubmitField, validators, ValidationError
from wtforms.validators import DataRequired, EqualTo, Length, Optional
from werkzeug.security import check_password_hash
from app.models.users import UsersModel

def invalid_credentials(form, field):
    email_entered = form.email.data
    password_entered = field.data

    user = UsersModel.query.filter_by(email=form.email.data).first()
    if not user or not check_password_hash(user.password, password):
        flash('Please check your login details and try again.')
        return redirect(url_for('auth.login'))

class LoginForm(FlaskForm):
    email = StringField('Email', [
        validators.InputRequired(message='Email Required')
        ])
    password = PasswordField('Password', validators=[DataRequired()])
    submit = SubmitField('Log In')

app/forms/registers.py
from flask_wtf import FlaskForm
from wtforms import Form, StringField, PasswordField, SubmitField, validators
from wtforms.validators import DataRequired
from flask_wtf import FlaskForm, RecaptchaField
from app.models.users import UsersModel

class RegisterForm(FlaskForm):
    username = StringField('Username', [
        validators.InputRequired(message='Username Required')
        ])
    full_name = StringField('Full name', [
        validators.InputRequired(message='Full Name Required')
        ])
    email = StringField('Email', [
        validators.InputRequired(message='Email Required')
        ])
    password = PasswordField('Password', [
        validators.DataRequired(),
        validators.InputRequired(message='Password Required'),
        validators.EqualTo('confirm_password', message='Passwords must match')
    ])
    confirm_password = PasswordField('Repeat Password', [
        validators.InputRequired(message='Confirm Password')
    ])
    
    submit = SubmitField('Submit')

app/views/auths.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import LoginManager, login_user, current_user, login_required, logout_user, UserMixin

from app.forms.registers import RegisterForm
from app.forms.login import LoginForm
from app.forms.edit import EditProfileForm
from app.models.users import UsersModel
from app.extensions._db import db

auth = Blueprint('auth', __name__)

@auth.route('/register', methods=('GET', 'POST'))
def register():

    form = RegisterForm()
    if request.method == 'POST':

        user = UsersModel(username=form.username.data, full_name=form.full_name.data, email=form.email.data)
        user.set_password(form.password.data)

        db.session.add(user)
        db.session.commit()
        flash('Thanks for registering')
        return redirect(url_for('auth.login'))

    return render_template('/auths/register.html', form=form)

@auth.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.dashboard'))

    form = LoginForm()

    #allow user to login if no validation error
    if form.validate_on_submit():
        user = UsersModel.query.filter_by(email=form.email.data).first()
        if user is None or not user.check_password(form.password.data):
            flash('Invalid username or password')
            return redirect(url_for('auth.login'))
        login_user(user)
        return redirect(url_for('main.dashboard'))

    return render_template('/auths/login.html', form=form)

@auth.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for('index'))

@auth.route('/edit', methods=['GET', 'POST'])
@login_required
def edit():
    form = EditProfileForm()

    if form.validate_on_submit():
        current_user.username = form.username.data
        current_user.full_name = form.full_name.data
        current_user.email = form.email.data
        current_user.password = form.password.data
        db.session.commit()
        flash('Your changes have been saved.')
        return redirect(url_for('edit'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.full_name.data = current_user.full_name
        form.email.data = current_user.email
        form.password.data = current_user.password
    return render_template('/auths/edit_profile.html', form=form)

app/templates/auths/edit_profile.html
{% extends 'base.html' %}

{% block content %}
<!-- Main Content -->
<div id="content">

    <!-- End of Topbar -->

    <!-- Begin Page Content -->
    <div class="container-fluid">

        <!-- Page Heading -->
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">Edit Profile</h1>
        </div>

        <!-- Content Row -->
        <div class="row">
            <div class="col-xl-6 col-md-6 mb-4">
                <div class="col">
                {% for message in get_flashed_messages() %}
                <div class="alert alert-warning">
                <button
                type="button"
                class="close"
                data-dismiss="alert">
                x
                </button>
                {{ message }}
                {% endfor %}
                </div>
                <form method="POST" action="{{ url_for('auth.register') }}">
                    {{ form.csrf_token }}
                    <div class="form-group">
                        <label for="exampleFormControlInput1">Username</label>
                        {{ form.username(class_="form-control", id="exampleFormControlInput1", placeholder="Username") }}
                        {% for error in form.username.errors %}
                        <span style="color: red;">[{{ error }}]</span>
                        {% endfor %}
                    </div>
                    <div class="form-group">
                        <label for="exampleFormControlInput1">Full Name</label>
                        {{ form.full_name(class_="form-control", id="exampleFormControlInput1", placeholder="Full Name") }}
                        {% for error in form.full_name.errors %}
                        <span style="color: red;">[{{ error }}]</span>
                        {% endfor %}
                    </div>
                    <div class="form-group">
                        <label for="exampleFormControlInput1">Email Address</label>
                        {{ form.email(class_="form-control", id="exampleFormControlInput1", placeholder="name@example.com") }}
                        {% for error in form.email.errors %}
                        <span style="color: red;">[{{ error }}]</span>
                        {% endfor %}
                    </div>
                    <div class="row">
                        <div class="col">
                            <label for="exampleFormControlInput1">Password</label>
                            {{ form.password(class_="form-control") }}
                            {% for error in form.password.errors %}
                            <span style="color: red;">[{{ error }}]</span>
                            {% endfor %}
                        </div>
                        <div class="col">
                            <label for="exampleFormControlInput1">Retype Password</label>
                            {{ form.confirm_password(class_="form-control") }}
                            {% for error in form.confirm_password.errors %}
                            <span style="color: red;">[{{ error }}]</span>
                            {% endfor %}
                        </div>
                    </div>
                    <hr>
                    <button class="btn btn-primary btn-user btn-block">
                        Edit Profile
                    </button>
                  </form>
            </div>
        </div>

        <!-- Content Row -->


    </div>
    <!-- /.container-fluid -->

</div>
<!-- End of Main Content -->
{% endblock %}

app/templates/auths/login.html
{% extends 'index.html' %}

{% block content %}

<div class="container">

  <!-- Outer Row -->
  <div class="row justify-content-center">

      <div class="col-xl-10 col-lg-12 col-md-9">

          <div class="card o-hidden border-0 shadow-lg my-5">
              <div class="card-body p-0">
                  <!-- Nested Row within Card Body -->
                  <div class="row">
                      <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>
                      <div class="col-lg-6">
                          <div class="p-5">
                              <div class="text-center">
                                  <h1 class="h4 text-gray-900 mb-4">Welcome Back!</h1>
                              </div>
                              <div class="col py-3 px-lg-5">
                                {% for message in get_flashed_messages() %}
                                <div class="alert alert-warning">
                                <button
                                type="button"
                                class="close"
                                data-dismiss="alert">
                                x
                                </button>
                                {{ message }}
                                {% endfor %}
                              </div>
                              <form class="user" method="POST" action="{{ url_for('auth.login') }}">
                                  {{ form.csrf_token }}
                                  <div class="form-group">
                                    {{ form.email(class_="form-control form-control-user", placeholder="Email Adress...") }}
                                  </div>
                                  <div class="form-group">
                                    {{ form.password(class_="form-control form-control-user", placeholder="Password") }}
                                  </div>
                                  <div class="form-group">
                                      <div class="custom-control custom-checkbox small">
                                          <input type="checkbox" class="custom-control-input" id="customCheck">
                                          <label class="custom-control-label" for="customCheck">Remember
                                              Me</label>
                                      </div>
                                  </div>
                                  <button class="btn btn-primary btn-user btn-block">
                                    Login
                                  </button>
            
                              </form>
                              <hr>
                              <div class="text-center">
                                  <a class="small" href="forgot-password.html">Forgot Password?</a>
                              </div>
                              <div class="text-center">
                                  <a class="small" href="{{ url_for('auth.register') }}">Create an Account!</a>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>

      </div>

  </div>

</div>

{% endblock %}

app/templates/auths/register.html
{% extends 'index.html' %}

{% block content %}
<div class="container">

  <div class="card o-hidden border-0 shadow-lg my-5">
      <div class="card-body p-0">
          <!-- Nested Row within Card Body -->
          <div class="row">
              <div class="col-lg-5 d-none d-lg-block bg-register-image"></div>
              <div class="col-lg-7">
                  <div class="p-5">
                      <div class="text-center">
                          <h1 class="h4 text-gray-900 mb-4">Create an Account!</h1>
                      </div>
                      <div class="col py-3 px-lg-5">
                        {% for message in get_flashed_messages() %}
                        <div class="alert alert-warning">
                        <button
                        type="button"
                        class="close"
                        data-dismiss="alert">
                        x
                        </button>
                        {{ message }}
                        {% endfor %}
                      </div>
                      <form class="user" method="POST" action="{{ url_for('auth.register') }}">
                          {{ form.csrf_token }}
                          <div class="form-group">
                            {{ form.username(class_="form-control form-control-user", placeholder="Username") }}
                            {% for error in form.username.errors %}
                            <span style="color: red;">[{{ error }}]</span>
                            {% endfor %}
                          </div>
                          
                          <div class="form-group">
                            {{ form.full_name(class_="form-control form-control-user", placeholder="Full Name") }}
                            {% for error in form.full_name.errors %}
                            <span style="color: red;">[{{ error }}]</span>
                            {% endfor %}
                          </div>

                          <div class="form-group">
                            {{ form.email(class_="form-control form-control-user", placeholder="Email") }}
                            {% for error in form.email.errors %}
                            <span style="color: red;">[{{ error }}]</span>
                            {% endfor %}
                          </div>

                          <div class="form-group row">
                              <div class="col-sm-6 mb-3 mb-sm-0">
                                {{ form.password(class_="form-control form-control-user", placeholder="Password") }}
                                {% for error in form.password.errors %}
                                <span style="color: red;">[{{ error }}]</span>
                                {% endfor %}
                              </div>
                              <div class="col-sm-6">
                                {{ form.confirm_password(class_="form-control form-control-user", placeholder="Retype Password") }}
                                {% for error in form.confirm_password.errors %}
                                <span style="color: red;">[{{ error }}]</span>
                                {% endfor %}
                              </div>
                          </div>
                          <button class="btn btn-primary btn-user btn-block">
                              Register Account
                          </button>
                      </form>
                      <hr>
                      <div class="text-center">
                          <a class="small" href="forgot-password.html">Forgot Password?</a>
                      </div>
                      <div class="text-center">
                          <a class="small" href="{{ url_for('auth.login') }}">Already have an account? Login!</a>
                      </div>
                  </div>
              </div>
          </div>
      </div>
  </div>

</div>

{% endblock %}